app/urls.py
from django.urls import path
from .views.tarefas_views import *
from .views.usuarios_views import *

urlpatterns = [
    path('listar_tarefas/', listar_tarefas, name='listar_tarefas'),
    path('cadastrar_tarefas/', cadastrar_tarefas, name='cadastrar_tarefas'),
    path('editar_tarefas/<int:id>', editar_tarefas, name='editar_tarefas'),
    path('remover_tarefas/<int:id>', remover_tarefas, name='remover_tarefas'),
    path('cadastrar_usuarios/', cadastrar_usuarios, name='cadastrar_usuarios'),
    path('logar_usuarios/', logar_usuarios, name='logar_usuarios'),
    path('deslogar_usuarios/', deslogar_usuarios, name='deslogar_usuarios'),
]

app/models.py
from django.db import models
from django.contrib.auth.models import User


class Tarefa(models.Model):
    PRIORIDADE_CHOICES = [
        ("A", "Alta"),
        ("N", "Normal"),
        ("B", "Baixa"),
    ]
    titulo = models.CharField(max_length=30, null=False, blank=False)
    descricao = models.CharField(max_length=100, null=False, blank=False)
    data_expiracao = models.DateField(null=False, blank=False)
    prioridade = models.CharField(max_length=1, choices=PRIORIDADE_CHOICES, null=False, blank=False)
    usuario = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

app/forms.py
from django import forms
from .models import Tarefa

class TarefaForm(forms.ModelForm):
    class Meta:
        model = Tarefa
        exclude = ('usuario',)
        fields = '__all__'

app/views/tarefas_views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from ..forms import TarefaForm
from ..entidades.tarefa import Tarefa
from ..services import tarefa_service

@login_required()
def listar_tarefas(request):
    tarefas = tarefa_service.listar_tarefas(request.user)
    return render(request, 'tarefas/listar_tarefas.html', {"tarefas": tarefas})

@login_required()
def cadastrar_tarefas(request):
    if request.method == "POST":
        form_tarefa = TarefaForm(request.POST)
        if form_tarefa.is_valid():
            titulo = form_tarefa.cleaned_data["titulo"]
            descricao = form_tarefa.cleaned_data["descricao"]
            data_expiracao = form_tarefa.cleaned_data["data_expiracao"]
            prioridade = form_tarefa.cleaned_data["prioridade"]
            tarefa_nova = Tarefa(titulo=titulo, descricao=descricao, data_expiracao=data_expiracao,
                                 prioridade=prioridade, usuario=request.user)
            tarefa_service.cadastrar_tarefas(tarefa_nova)
            return redirect('listar_tarefas')
    else:
        form_tarefa = TarefaForm()
    return render(request, 'tarefas/form_tarefa.html', {"form_tarefa": form_tarefa})

@login_required()
def editar_tarefas(request, id):
    tarefa_bd = tarefa_service.listar_tarefas_id(id)
    if tarefa_bd.usuario != request.user:
        return HttpResponse("Acesso não permitido")
    form_tarefa = TarefaForm(request.POST or None, instance=tarefa_bd)
    if form_tarefa.is_valid():
        titulo = form_tarefa.cleaned_data["titulo"]
        descricao = form_tarefa.cleaned_data["descricao"]
        data_expiracao = form_tarefa.cleaned_data["data_expiracao"]
        prioridade = form_tarefa.cleaned_data["prioridade"]
        tarefa_nova = Tarefa(titulo=titulo, descricao=descricao, data_expiracao=data_expiracao,
                             prioridade=prioridade, usuario=request.user)
        tarefa_service.editar_tarefas(tarefa_bd, tarefa_nova)
        return redirect('listar_tarefas')
    return render(request, 'tarefas/form_tarefa.html', {'form_tarefa': form_tarefa})

@login_required()
def remover_tarefas(request, id):
    tarefa_bd = tarefa_service.listar_tarefas_id(id)
    if tarefa_bd.usuario != request.user:
        return HttpResponse("Acesso não permitido")
    if request.method == "POST":
        tarefa_service.remover_tarefas(tarefa_bd)
        return redirect('listar_tarefas')
    return render(request, 'tarefas/confirma_exclusao.html', {'tarefa': tarefa_bd})

app/views/usuarios_views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.shortcuts import redirect, render


def cadastrar_usuarios(request):
    if request.method == "POST":
        form_usuarios = UserCreationForm(request.POST)
        if form_usuarios.is_valid():
            form_usuarios.save()
            return redirect('listar_tarefas')
    else:
            form_usuarios = UserCreationForm()
    return render(request, 'usuarios/form_usuarios.html', {"form_usuarios": form_usuarios})


def logar_usuarios(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        usuario = authenticate(request, username=username, password=password)
        if usuario is not None:
            login(request, usuario)
            return redirect('listar_tarefas')
        else:
            messages.error(request, 'Login ou sennha inválidos')
            return redirect('logar_usuarios')
    else:
        form_login = AuthenticationForm()
        return render(request, 'usuarios/login.html', {"form_login": form_login})


def deslogar_usuarios(request):
    logout(request)
    return redirect('logar_usuarios')

app/templates/base.html
<!DOCTYPE html>
{% load static from staticfiles %}
<html lang="en">
<link>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="icon" type="imagem/ico" href="{% static 'app/img/favicon.ico' %}" />
    <link rel="stylesheet" href="{% static 'app/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'app/css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

     <title>UTask - Gerenciador de Tarefas</title>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#"><i class="fa fa-tasks" aria-hidden="true" style="color: #4682b4"></i> UTask</a>
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'logar_usuarios' %}"> Logar </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'deslogar_usuarios' %}"> Logoff </a>
        </li>
    </ul>
  </div>
</nav>
<main class="container">
   {% block conteudo %}

    {% endblock conteudo %}
</main>

<footer class="footer mt-auto py-3 text-center">
    <div class="container">
        <span class="text-muted">Desiree Fraga - 2019 &copy | fragadeh.a@gmail.com</span>
    </div>
</footer>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="{% static 'app/js/bootstrap.min.js' %}"></script>
</body>
</html>

app/templates/tarefas/confirma_exclusao.html
{% extends 'base.html' %}

{% block conteudo %}
<br/>
<div class="alert alert-danger ajuste">
        <p class="alerta">Tem certeza que deseja excluir a tarefa abaixo?</p>
</div>
<div>
    <div class="card nb-3 ajuste">
        <div class="card-header">
            <h5 class="card-ti  tle">{{tarefa.titulo}}</h5>
        </div>
        <div class="card-body">
            <p>{{tarefa.descricao}}</p>
        </div>
            <div class="card-footer">Expira em: {{tarefa.data_expiracao}}</div>
        <hr>
         <form method="post" class="centraliza">
                {% csrf_token %}
                <button class="btn btn-danger btn-sm" type="submit">Excluir</button> | <a href="{% url 'listar_tarefas' %}"><input type="button" class="btn btn-info btn-sm nb-3" value="Voltar"></a>
         </form>
    </div>
</div>
{% endblock conteudo %}

app/templates/tarefas/form_tarefa.html
{% extends 'base.html' %}
{% load meus_filtros %}
{% block conteudo %}
<br/>
<div class="centraliza">
<form method="post" class="ajuste">
    {% csrf_token %}
    <div class="form-group">
        {{ form_tarefa.titulo.errors }}
        <label>Titulo: </label>
        {{ form_tarefa.titulo|addclass:'form-control'}}
    </div>

     <div class="form-group">
        {{ form_tarefa.descricao.errors }}
        <label>Descrição: </label>
        {{ form_tarefa.descricao|addclass:'form-control' }}
    </div>

     <div class="form-group">
        {{ form_tarefa.data_expiracao.errors }}
        <label>Data de Expiração: </label>
        {{ form_tarefa.data_expiracao|addclass:'form-control' }}
    </div>

     <div class="form-group">
        {{ form_tarefa.prioridade.errors }}
        <label>Prioridade: </label>
        {{ form_tarefa.prioridade|addclass:'form-control' }}
    </div>

    <div class="form-group">
        <input type="submit" class="btn btn-block btn-info" value="Salvar">
    </div>
</form>
</div>
    <div class="form-group">
        <a href="{% url 'listar_tarefas' %}"><input type="button" class="btn btn-default  " value="<"></a>
    </div>
{% endblock conteudo %}

app/templates/tarefas/listar_tarefas.html
{% extends 'base.html' %}

{% block conteudo %}

<a href="{% url 'cadastrar_tarefas' %}"><input type="button" class="btn btn-info nb-3 botao" value="Cadastrar nova tarefa"></a>
{% for tarefa in tarefas %}
<div>
    <div class="card nb-3 ajuste">
        <div class="card-header">
            <span class="decoracao-cartao">Prioridade:</span> {{tarefa.get_prioridade_display}}
        </div>
        <div class="card-body">
            <h5 class="card-title">{{tarefa.titulo}}</h5>
            <p class="card-text">{{tarefa.descricao}}</p>
        </div>
        <div class="card-footer">
            <span class="decoracao-cartao">Expira em:</span> {{tarefa.data_expiracao}}
        <hr>
            <a href="{% url 'editar_tarefas' tarefa.id %}">Alterar tarefa</a> |  <a href="{% url 'remover_tarefas' tarefa.id %}">Excluir tarefa</a>
        </div>
</div>
</div>
{% endfor %}

{% endblock conteudo %}

app/templates/usuarios/form_usuarios.html
{% extends 'base.html' %}
{% load meus_filtros %}
{% block conteudo %}
<br/>
<div class="centraliza">
    <form method="post" class="ajuste">
        {% csrf_token %}
        <div class="form-group">
            {{ form_usuarios.username.errors}}
            <label>Escolha seu login: </label>
            {{ form_usuarios.username|addclass:'form-control' }}
        </div>

        <div class="form-group">
            {{ form_usuarios.password1.errors}}
            <label>Escolha sua senha: </label>
            {{ form_usuarios.password1|addclass:'form-control' }}
        </div>

        <div class="form-group">
            {{ form_usuarios.password2.errors}}
            <label>Confirme sua senha: </label>
            {{ form_usuarios.password2|addclass:'form-control' }}
        </div>

        <div class="form-group">
            <input type="submit" value="Cadastrar" class="btn btn-info">
        </div>
    </form>
</div>
{% endblock conteudo %}

app/templates/usuarios/login.html
{% extends 'base.html' %}

{% block conteudo %}

{% load meus_filtros %}
    <form method="post" class="form-signin centraliza-login">
        <img class="mb-4" src="http://www.salesforcebrasil.com.br/wp-content/uploads/2014/06/Cloud-Plain-Blue.png" alt="" width="85" height="85">
        <hr>
        {% csrf_token %}
        {% for message in messages%}
            <div class="alert alert-danger">
                {{ message }}
        {% endfor %}
            </div>
        <div class="form-group ajuste-login">
            {{ form_login.username.errors}}
            <label>Login: </label>
            {{ form_login.username|addclass:'form-control' }}
        </div>
        <br/>
        <div class="form-group ajuste-login">
            {{ form_login.password.errors}}
            <label>Senha: </label>
            {{ form_login.password|addclass:'form-control' }}
        </div>
        <br/>
        <div class="form-group ajuste-login">
            <input type="submit" value="Entrar" class="btn btn-info">
        </div>
        <br/>
        <a href="{% url 'cadastrar_usuarios' %}">Ainda não possui cadastro? - Clique aqui</a>
    </form>

{% endblock conteudo %}